<?php

namespace AppBundle\Repository;

/**
 * Info_opldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Info_opldRepository extends \Doctrine\ORM\EntityRepository
{
}
