<?php

namespace AppBundle\Repository;

/**
 * IntakeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IntakeRepository extends \Doctrine\ORM\EntityRepository
{
}
