<?php

namespace AppBundle\Repository;

/**
 * OpleidingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpleidingRepository extends \Doctrine\ORM\EntityRepository
{
}
